version: 0.2
run-as: root

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - yum update -y
      - yum install maven -y
      - yum install awscli -y
      - yum install -y yum-utils
      - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - yum -y install terraform -y
  pre_build:
    commands:
      - java -version
      - mvn -version 
      - aws --version
      - terraform --version
  pre_build:
    commands:
      - echo 'Pre Build Phase ...'
      - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - terraform init
      - mvn install
  build:
    commands:
      - echo 'Build Phase ...'
      - mvn package
      - terraform apply -auto-approve -var="filename=$FILENAME"
artifacts:
  files:
    - $FILENAME
  