version: 0.2
run-as: root

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - yum update -y
      - yum install maven -y
  pre_build:
    commands:
      - java -version
      - mvn -version 
  pre_build:
    commands:
      - echo 'Pre Build Phase ...'
  build:
    commands:
      - echo 'Build Phase ...'
      - mvn install
      - mvn package -DskipTests -Dmaven.javadoc.skip=true
      - #! /bin/bash
      - ls target
      - dir=$(ls target)
      - arr=($dir)
      - lambda_jar_file=${arr[0]}
      - echo $lambda_jar_file
artifacts:
  files:
    - '**/*'
  