version: 0.2
run-as: root

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - yum update -y
      - yum install maven -y
  pre_build:
    commands:
      - java -version
      - mvn -version 
  pre_build:
    commands:
      - echo 'Pre Build Phase ...'
      - mvn install
  build:
    commands:
      - echo 'Build Phase ...'
      - mvn package
      - #! /bin/bash
      - dir=($(ls target))
      - lambda_jar_file=${dir[0]}
      - echo $lambda_jar_file
artifacts:
  files:
    - target/QR2HL7-1.0-SNAPSHOT.jar
  